name: musedme
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

#  AGORA packages user for video/audio call & chat
  agora_rtc_engine: ^5.3.0
  agora_rtm: ^1.1.1

  badges: ^2.0.3

#  cached_video_player: ^2.0.3
  country_picker: ^2.0.16
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.4.0
  file_picker: ^5.2.2
  flutter_svg: ^1.1.5
  flutter_vector_icons: ^1.0.0
  flutter_speed_dial: ^6.2.0

# Firebase used for push notification
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4

# Used to handle local notifications
  awesome_notifications: ^0.7.2

#  Used for state management
  get: ^4.6.5
  get_storage: ^2.0.3

  gallery_saver: ^2.3.2

  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.4.3
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  ringtone_player: ^0.1.1

#  IMGLY Photo & Video editor
  photo_editor_sdk: ^2.7.0
  video_editor_sdk: ^2.7.0

  timeago: ^3.3.0
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.1
  better_player:
    git:
      url: https://github.com/matthewrice345/betterplayer.git
      ref: Issue1057 # branch name
  #  cached_network_image: ^3.2.2
  palette_generator: ^0.3.3+2
  flutter_stripe: ^6.0.0
  swipeable_button_view: ^0.0.2
  google_sign_in: ^5.2.1
  firebase_auth: ^3.11.2
  just_audio: ^0.9.30
  audio_session: ^0.1.10
  grouped_list: ^5.1.2
  audio_video_progress_bar: ^0.11.0
#  flutter_audio_cutter: ^1.0.3+1
  flutter_file_saver: ^0.6.1+1
  ffmpeg_kit_flutter_audio: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/icons/
   - assets/lottie/


  fonts:
   - family: Larsseit
     fonts:
      - asset: assets/fonts/Larsseit/Larsseit-Thin.otf
      - asset: assets/fonts/Larsseit/Larsseit-Light.otf
      - asset: assets/fonts/Larsseit/Larsseit.otf
        weight: 400
      - asset: assets/fonts/Larsseit/Larsseit-Medium.otf
      - asset: assets/fonts/Larsseit/Larsseit-Bold.otf
      - asset: assets/fonts/Larsseit/Larsseit-ExtraBold.otf
