// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHN4CTV3nNcu89OaXrMiCWPWtnle1vZQ',
    appId: '1:760964256580:web:7489b639963b9e2bc1bd11',
    messagingSenderId: '760964256580',
    projectId: 'musedbyme-220ef',
    authDomain: 'musedbyme-220ef.firebaseapp.com',
    storageBucket: 'musedbyme-220ef.appspot.com',
    measurementId: 'G-RXQP128ZVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-T9lTekwFXsDoVkOaUXbaJcmv9_oJ70',
    appId: '1:760964256580:android:8f0757078787a0a4c1bd11',
    messagingSenderId: '760964256580',
    projectId: 'musedbyme-220ef',
    storageBucket: 'musedbyme-220ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUE6q0k28xCSL0LrKGslCbqWQGa753DpI',
    appId: '1:760964256580:ios:ffa2336e021fbbd2c1bd11',
    messagingSenderId: '760964256580',
    projectId: 'musedbyme-220ef',
    storageBucket: 'musedbyme-220ef.appspot.com',
    iosClientId: '760964256580-lfpvs22phagevmg6kithb20msl1taio4.apps.googleusercontent.com',
    iosBundleId: 'com.example.musedme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUE6q0k28xCSL0LrKGslCbqWQGa753DpI',
    appId: '1:760964256580:ios:ffa2336e021fbbd2c1bd11',
    messagingSenderId: '760964256580',
    projectId: 'musedbyme-220ef',
    storageBucket: 'musedbyme-220ef.appspot.com',
    iosClientId: '760964256580-lfpvs22phagevmg6kithb20msl1taio4.apps.googleusercontent.com',
    iosBundleId: 'com.example.musedme',
  );
}
