///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  // SVG IMAGES
  static const String iconsAdd = 'assets/icons/add.svg';
  static const String iconsComment = 'assets/icons/comment.svg';
  static const String iconsDelete = 'assets/icons/delete.svg';
  static const String iconsEditProfile = 'assets/icons/edit_profile.svg';
  static const String iconsEye = 'assets/icons/eye.svg';
  static const String iconsFacebook = 'assets/icons/facebook.svg';
  static const String iconsFavorites = 'assets/icons/Favorites.svg';
  static const String iconsFeed = 'assets/icons/Feed.svg';
  static const String iconsGoogle = 'assets/icons/google.svg';
  static const String iconsHeart = 'assets/icons/heart.svg';
  static const String iconsLive = 'assets/icons/live.svg';
  static const String iconsMessages = 'assets/icons/Messages.svg';
  static const String iconsProfile = 'assets/icons/Profile.svg';
  static const String iconsShare = 'assets/icons/share.svg';
  static const String iconsTwitter = 'assets/icons/twitter.svg';
  static const String iconsUploadImage = 'assets/icons/upload_image.svg';
  static const String iconsVerified = 'assets/icons/verified.svg';
  static const String iconsVideos = 'assets/icons/Videos.svg';
  static const String iconsDownloadedVideos = 'assets/icons/downloaded_videos.svg';
  static const String iconsHistory = 'assets/icons/history.svg';
  static const String iconsWatchLater = 'assets/icons/watch_later.svg';

  // PNG IMAGES
  static const String iconsLogo = 'assets/icons/logo.png';
  static const String iconsSmileyFace = 'assets/icons/smiling_face.png';

  // LOTTIE ANIMATIONS
  static const String loader = 'assets/lottie/lf30.json';

  static const List<String> menuIcons = [
    iconsFeed,
    iconsVideos,
    iconsFavorites,
    iconsMessages,
    iconsProfile,
  ];
}
